//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Oereb.Service.DataContracts.Model.v10
{ 

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract")]
[System.Xml.Serialization.XmlRootAttribute("GetExtractByIdResponse", Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract", IsNullable=false)]
public partial class GetExtractByIdResponseType {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Extract", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("embeddable", typeof(GetExtractByIdResponseTypeEmbeddable))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract")]
public partial class GetExtractByIdResponseTypeEmbeddable {
    
    private System.DateTime cadasterStateField;
    
    private string cadasterOrganisationNameField;
    
    private string dataownerNameCadastralSurveyingField;
    
    private System.DateTime transferFromSourceCadastralSurveyingField;
    
    private GetExtractByIdResponseTypeEmbeddableDatasource datasourceField;
    
    private byte[] pdfField;
    
    /// <remarks/>
    public System.DateTime cadasterState {
        get {
            return this.cadasterStateField;
        }
        set {
            this.cadasterStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string cadasterOrganisationName {
        get {
            return this.cadasterOrganisationNameField;
        }
        set {
            this.cadasterOrganisationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string dataownerNameCadastralSurveying {
        get {
            return this.dataownerNameCadastralSurveyingField;
        }
        set {
            this.dataownerNameCadastralSurveyingField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime transferFromSourceCadastralSurveying {
        get {
            return this.transferFromSourceCadastralSurveyingField;
        }
        set {
            this.transferFromSourceCadastralSurveyingField = value;
        }
    }
    
    /// <remarks/>
    public GetExtractByIdResponseTypeEmbeddableDatasource datasource {
        get {
            return this.datasourceField;
        }
        set {
            this.datasourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] pdf {
        get {
            return this.pdfField;
        }
        set {
            this.pdfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract")]
public partial class GetExtractByIdResponseTypeEmbeddableDatasource {
    
    private Theme topicField;
    
    private string dataownerNameField;
    
    private System.DateTime transferFromSourceField;
    
    /// <remarks/>
    public Theme topic {
        get {
            return this.topicField;
        }
        set {
            this.topicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string dataownerName {
        get {
            return this.dataownerNameField;
        }
        set {
            this.dataownerNameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime transferFromSource {
        get {
            return this.transferFromSourceField;
        }
        set {
            this.transferFromSourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract")]
[System.Xml.Serialization.XmlRootAttribute("GetEGRIDResponse", Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract", IsNullable=false)]
public partial class GetEGRIDResponseType {
    
    private string[] egridField;
    
    private string[] numberField;
    
    private string[] identDNField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("egrid", DataType="token")]
    public string[] egrid {
        get {
            return this.egridField;
        }
        set {
            this.egridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("number", DataType="token")]
    public string[] number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("identDN", DataType="token")]
    public string[] identDN {
        get {
            return this.identDNField;
        }
        set {
            this.identDNField = value;
        }
    }
}

    public partial class GetEGRIDResponseTypeExtended : GetEGRIDResponseType
    {
        private string[] shapeField;
        private string[] kindOfField;

        [System.Xml.Serialization.XmlElementAttribute("shape", DataType = "token")]
        public string[] shape
        {
            get
            {
                return this.shapeField;
            }
            set
            {
                this.shapeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("kindOf", DataType = "token")]
        public string[] kindOf
        {
            get
            {
                return this.kindOfField;
            }
            set
            {
                this.kindOfField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract")]
[System.Xml.Serialization.XmlRootAttribute("GetCapabilitiesResponse", Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract", IsNullable=false)]
public partial class GetCapabilitiesResponseType {
    
    private Theme[] topicField;
    
    private string[] municipalityField;
    
    private string[] flavourField;
    
    private string[] languageField;
    
    private string[] crsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("topic")]
    public Theme[] topic {
        get {
            return this.topicField;
        }
        set {
            this.topicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("municipality", DataType="integer")]
    public string[] municipality {
        get {
            return this.municipalityField;
        }
        set {
            this.municipalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("flavour", DataType="token")]
    public string[] flavour {
        get {
            return this.flavourField;
        }
        set {
            this.flavourField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("language", DataType="token")]
    public string[] language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("crs", DataType="token")]
    public string[] crs {
        get {
            return this.crsField;
        }
        set {
            this.crsField = value;
        }
    }
}

}
