//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Oereb.Service.DataContracts.Model.v20
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData", IsNullable = false)]
    public partial class Extract
    {

        private System.DateTime creationDateField;

        private SignatureType signatureField;

        private Theme[] concernedThemeField;

        private Theme[] notConcernedThemeField;

        private Theme[] themeWithoutDataField;

        private object itemField;

        private object item1Field;

        private object item2Field;

        private object item3Field;

        private string extractIdentifierField;

        private object item4Field;

        private GeneralInformation[] generalInformationField;

        private Glossary[] glossaryField;

        private RealEstate_DPR realEstateField;

        private Disclaimer[] disclaimerField;

        private Office pLRCadastreAuthorityField;

        private System.DateTime updateDateCSField;

        private extensions extensionsField;

        private string idField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public System.DateTime CreationDate
        {
            get
            {
                return this.creationDateField;
            }
            set
            {
                this.creationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConcernedTheme")]
        public Theme[] ConcernedTheme
        {
            get
            {
                return this.concernedThemeField;
            }
            set
            {
                this.concernedThemeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NotConcernedTheme")]
        public Theme[] NotConcernedTheme
        {
            get
            {
                return this.notConcernedThemeField;
            }
            set
            {
                this.notConcernedThemeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ThemeWithoutData")]
        public Theme[] ThemeWithoutData
        {
            get
            {
                return this.themeWithoutDataField;
            }
            set
            {
                this.themeWithoutDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LogoPLRCadastre", typeof(byte[]), DataType = "base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("LogoPLRCadastreRef", typeof(string), DataType = "anyURI")]
        public object LogoPLRCadastre
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FederalLogo", typeof(byte[]), DataType = "base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("FederalLogoRef", typeof(string), DataType = "anyURI")]
        public object FederalLogo
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CantonalLogo", typeof(byte[]), DataType = "base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("CantonalLogoRef", typeof(string), DataType = "anyURI")]
        public object CantonalLogo
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MunicipalityLogo", typeof(byte[]), DataType = "base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("MunicipalityLogoRef", typeof(string), DataType = "anyURI")]
        public object MunicipalityLogo
        {
            get
            {
                return this.item3Field;
            }
            set
            {
                this.item3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string ExtractIdentifier
        {
            get
            {
                return this.extractIdentifierField;
            }
            set
            {
                this.extractIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QRCode", typeof(byte[]), DataType = "base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("QRCodeRef", typeof(string), DataType = "anyURI")]
        public object Item4
        {
            get
            {
                return this.item4Field;
            }
            set
            {
                this.item4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GeneralInformation")]
        public GeneralInformation[] GeneralInformation
        {
            get
            {
                return this.generalInformationField;
            }
            set
            {
                this.generalInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Glossary")]
        public Glossary[] Glossary
        {
            get
            {
                return this.glossaryField;
            }
            set
            {
                this.glossaryField = value;
            }
        }

        /// <remarks/>
        public RealEstate_DPR RealEstate
        {
            get
            {
                return this.realEstateField;
            }
            set
            {
                this.realEstateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Disclaimer")]
        public Disclaimer[] Disclaimer
        {
            get
            {
                return this.disclaimerField;
            }
            set
            {
                this.disclaimerField = value;
            }
        }

        /// <remarks/>
        public Office PLRCadastreAuthority
        {
            get
            {
                return this.pLRCadastreAuthorityField;
            }
            set
            {
                this.pLRCadastreAuthorityField = value;
            }
        }

        /// <remarks/>
        public System.DateTime UpdateDateCS
        {
            get
            {
                return this.updateDateCSField;
            }
            set
            {
                this.updateDateCSField = value;
            }
        }

        /// <remarks/>
        public extensions extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Disclaimer
    {

        private LocalisedText[] titleField;

        private LocalisedMText[] contentField;

        private extensions extensionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedMText[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        public extensions extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class LocalisedText
    {

        private LanguageCode languageField;

        private bool languageFieldSpecified;

        private string textField;

        /// <remarks/>
        public LanguageCode Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LanguageSpecified
        {
            get
            {
                return this.languageFieldSpecified;
            }
            set
            {
                this.languageFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public enum LanguageCode
    {

        /// <remarks/>
        de,

        /// <remarks/>
        fr,

        /// <remarks/>
        it,

        /// <remarks/>
        rm,

        /// <remarks/>
        en,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class LocalisedMText
    {

        private LanguageCode languageField;

        private bool languageFieldSpecified;

        private string textField;

        /// <remarks/>
        public LanguageCode Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LanguageSpecified
        {
            get
            {
                return this.languageFieldSpecified;
            }
            set
            {
                this.languageFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData", IsNullable = false)]
    public partial class extensions
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Office
    {

        private LocalisedText[] nameField;

        private LocalisedUri[] officeAtWebField;

        private string uIDField;

        private string line1Field;

        private string line2Field;

        private string streetField;

        private string numberField;

        private string postalCodeField;

        private string cityField;

        private extensions extensionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedUri[] OfficeAtWeb
        {
            get
            {
                return this.officeAtWebField;
            }
            set
            {
                this.officeAtWebField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string Line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string Line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public extensions extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class LocalisedUri
    {

        private LanguageCode languageField;

        private bool languageFieldSpecified;

        private string textField;

        /// <remarks/>
        public LanguageCode Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LanguageSpecified
        {
            get
            {
                return this.languageFieldSpecified;
            }
            set
            {
                this.languageFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class DocumentType
    {

        private DocumentTypeCode codeField;

        private LocalisedText[] textField;

        /// <remarks/>
        public DocumentTypeCode Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public enum DocumentTypeCode
    {

        /// <remarks/>
        LegalProvision,

        /// <remarks/>
        Law,

        /// <remarks/>
        Hint,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Document
    {

        private DocumentType typeField;

        private LocalisedText[] titleField;

        private LocalisedText[] abbreviationField;

        private LocalisedText[] officialNumberField;

        private LocalisedUri[] textAtWebField;

        private string[] articleNumberField;

        private Lawstatus lawstatusField;

        private string indexField;

        private Office responsibleOfficeField;

        private extensions extensionsField;

        /// <remarks/>
        public DocumentType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] OfficialNumber
        {
            get
            {
                return this.officialNumberField;
            }
            set
            {
                this.officialNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedUri[] TextAtWeb
        {
            get
            {
                return this.textAtWebField;
            }
            set
            {
                this.textAtWebField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ArticleNumber", DataType = "normalizedString")]
        public string[] ArticleNumber
        {
            get
            {
                return this.articleNumberField;
            }
            set
            {
                this.articleNumberField = value;
            }
        }

        /// <remarks/>
        public Lawstatus Lawstatus
        {
            get
            {
                return this.lawstatusField;
            }
            set
            {
                this.lawstatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        public Office ResponsibleOffice
        {
            get
            {
                return this.responsibleOfficeField;
            }
            set
            {
                this.responsibleOfficeField = value;
            }
        }

        /// <remarks/>
        public extensions extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Lawstatus
    {

        private LawstatusCode codeField;

        private LocalisedText[] textField;

        /// <remarks/>
        public LawstatusCode Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public enum LawstatusCode
    {

        /// <remarks/>
        inForce,

        /// <remarks/>
        changeWithPreEffect,

        /// <remarks/>
        changeWithoutPreEffect,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class LegendEntry
    {

        private object itemField;

        private LocalisedText[] legendTextField;

        private string typeCodeField;

        private string typeCodelistField;

        private Theme themeField;

        private extensions extensionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Symbol", typeof(byte[]), DataType = "base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("SymbolRef", typeof(string), DataType = "anyURI")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] LegendText
        {
            get
            {
                return this.legendTextField;
            }
            set
            {
                this.legendTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string TypeCode
        {
            get
            {
                return this.typeCodeField;
            }
            set
            {
                this.typeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string TypeCodelist
        {
            get
            {
                return this.typeCodelistField;
            }
            set
            {
                this.typeCodelistField = value;
            }
        }

        /// <remarks/>
        public Theme Theme
        {
            get
            {
                return this.themeField;
            }
            set
            {
                this.themeField = value;
            }
        }

        /// <remarks/>
        public extensions extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Theme
    {

        private string codeField;

        private string subCodeField;

        private LocalisedText[] textField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class LocalisedBlob
    {

        private LanguageCode languageField;

        private bool languageFieldSpecified;

        private byte[] blobField;

        /// <remarks/>
        public LanguageCode Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LanguageSpecified
        {
            get
            {
                return this.languageFieldSpecified;
            }
            set
            {
                this.languageFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] Blob
        {
            get
            {
                return this.blobField;
            }
            set
            {
                this.blobField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Map
    {

        private LocalisedBlob[] imageField;

        private LocalisedUri[] referenceWMSField;

        private LegendEntry[] otherLegendField;

        private CoordType minField;

        private CoordType maxField;

        private string layerIndexField;

        private double layerOpacityField;

        private extensions extensionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedBlob[] Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedUri[] ReferenceWMS
        {
            get
            {
                return this.referenceWMSField;
            }
            set
            {
                this.referenceWMSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherLegend")]
        public LegendEntry[] OtherLegend
        {
            get
            {
                return this.otherLegendField;
            }
            set
            {
                this.otherLegendField = value;
            }
        }

        /// <remarks/>
        public CoordType min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        public CoordType max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string layerIndex
        {
            get
            {
                return this.layerIndexField;
            }
            set
            {
                this.layerIndexField = value;
            }
        }

        /// <remarks/>
        public double layerOpacity
        {
            get
            {
                return this.layerOpacityField;
            }
            set
            {
                this.layerOpacityField = value;
            }
        }

        /// <remarks/>
        public extensions extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Geometry
    {

        private GeometryType itemField;

        private Lawstatus lawstatusField;

        private string metadataOfGeographicalBaseDataField;

        private extensions extensionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line", typeof(PolylineType))]
        [System.Xml.Serialization.XmlElementAttribute("Point", typeof(CoordType))]
        [System.Xml.Serialization.XmlElementAttribute("Surface", typeof(SurfaceType))]
        public GeometryType Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public Lawstatus Lawstatus
        {
            get
            {
                return this.lawstatusField;
            }
            set
            {
                this.lawstatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string MetadataOfGeographicalBaseData
        {
            get
            {
                return this.metadataOfGeographicalBaseDataField;
            }
            set
            {
                this.metadataOfGeographicalBaseDataField = value;
            }
        }

        /// <remarks/>
        public extensions extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class RestrictionOnLandownership
    {

        private LocalisedMText[] legendTextField;

        private Theme themeField;

        private string typeCodeField;

        private string typeCodelistField;

        private Lawstatus lawstatusField;

        private string areaShareField;

        private double partInPercentField;

        private bool partInPercentFieldSpecified;

        private string lengthShareField;

        private string nrOfPointsField;

        private object itemField;

        private Geometry[] geometryField;

        private Map mapField;

        private Document[] legalProvisionsField;

        private Office responsibleOfficeField;

        private extensions extensionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedMText[] LegendText
        {
            get
            {
                return this.legendTextField;
            }
            set
            {
                this.legendTextField = value;
            }
        }

        /// <remarks/>
        public Theme Theme
        {
            get
            {
                return this.themeField;
            }
            set
            {
                this.themeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string TypeCode
        {
            get
            {
                return this.typeCodeField;
            }
            set
            {
                this.typeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string TypeCodelist
        {
            get
            {
                return this.typeCodelistField;
            }
            set
            {
                this.typeCodelistField = value;
            }
        }

        /// <remarks/>
        public Lawstatus Lawstatus
        {
            get
            {
                return this.lawstatusField;
            }
            set
            {
                this.lawstatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string AreaShare
        {
            get
            {
                return this.areaShareField;
            }
            set
            {
                this.areaShareField = value;
            }
        }

        /// <remarks/>
        public double PartInPercent
        {
            get
            {
                return this.partInPercentField;
            }
            set
            {
                this.partInPercentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartInPercentSpecified
        {
            get
            {
                return this.partInPercentFieldSpecified;
            }
            set
            {
                this.partInPercentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string LengthShare
        {
            get
            {
                return this.lengthShareField;
            }
            set
            {
                this.lengthShareField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string NrOfPoints
        {
            get
            {
                return this.nrOfPointsField;
            }
            set
            {
                this.nrOfPointsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Symbol", typeof(byte[]), DataType = "base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("SymbolRef", typeof(string), DataType = "anyURI")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Geometry")]
        public Geometry[] Geometry
        {
            get
            {
                return this.geometryField;
            }
            set
            {
                this.geometryField = value;
            }
        }

        /// <remarks/>
        public Map Map
        {
            get
            {
                return this.mapField;
            }
            set
            {
                this.mapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegalProvisions")]
        public Document[] LegalProvisions
        {
            get
            {
                return this.legalProvisionsField;
            }
            set
            {
                this.legalProvisionsField = value;
            }
        }

        /// <remarks/>
        public Office ResponsibleOffice
        {
            get
            {
                return this.responsibleOfficeField;
            }
            set
            {
                this.responsibleOfficeField = value;
            }
        }

        /// <remarks/>
        public extensions extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class RealEstateType
    {

        private RealEstateTypeCode codeField;

        private LocalisedText[] textField;

        /// <remarks/>
        public RealEstateTypeCode Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public enum RealEstateTypeCode
    {

        /// <remarks/>
        RealEstate,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.BuildingRight")]
        Distinct_and_permanent_rightsBuildingRight,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.right_to_spring_water")]
        Distinct_and_permanent_rightsright_to_spring_water,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.concession")]
        Distinct_and_permanent_rightsconcession,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.other")]
        Distinct_and_permanent_rightsother,

        /// <remarks/>
        Mineral_rights,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class RealEstate_DPR
    {
        private string numberField;

        private string identDNField;

        private string eGRIDField;

        private RealEstateType typeField;

        private CantonCode cantonField;

        private string municipalityNameField;

        private string municipalityCodeField;

        private string subunitOfLandRegisterField;

        private string subunitOfLandRegisterDesignationField;

        private string metadataOfGeographicalBaseDataField;

        private string landRegistryAreaField;

        private MultiSurfaceType limitField;

        private RestrictionOnLandownership[] restrictionOnLandownershipField;

        private Map planForLandRegisterField;

        private Map planForLandRegisterMainPageField;

        private extensions extensionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string IdentDN
        {
            get
            {
                return this.identDNField;
            }
            set
            {
                this.identDNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string EGRID
        {
            get
            {
                return this.eGRIDField;
            }
            set
            {
                this.eGRIDField = value;
            }
        }

        /// <remarks/>
        public RealEstateType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        /// <remarks/>
        public string TypeName { get; set; }

        /// <remarks/>
        public CantonCode Canton
        {
            get
            {
                return this.cantonField;
            }
            set
            {
                this.cantonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string MunicipalityName
        {
            get
            {
                return this.municipalityNameField;
            }
            set
            {
                this.municipalityNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string MunicipalityCode
        {
            get
            {
                return this.municipalityCodeField;
            }
            set
            {
                this.municipalityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string SubunitOfLandRegister
        {
            get
            {
                return this.subunitOfLandRegisterField;
            }
            set
            {
                this.subunitOfLandRegisterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string SubunitOfLandRegisterDesignation
        {
            get
            {
                return this.subunitOfLandRegisterDesignationField;
            }
            set
            {
                this.subunitOfLandRegisterDesignationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string MetadataOfGeographicalBaseData
        {
            get
            {
                return this.metadataOfGeographicalBaseDataField;
            }
            set
            {
                this.metadataOfGeographicalBaseDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string LandRegistryArea
        {
            get
            {
                return this.landRegistryAreaField;
            }
            set
            {
                this.landRegistryAreaField = value;
            }
        }

        /// <remarks/>
        public MultiSurfaceType Limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RestrictionOnLandownership")]
        public RestrictionOnLandownership[] RestrictionOnLandownership
        {
            get
            {
                return this.restrictionOnLandownershipField;
            }
            set
            {
                this.restrictionOnLandownershipField = value;
            }
        }

        /// <remarks/>
        public Map PlanForLandRegister
        {
            get
            {
                return this.planForLandRegisterField;
            }
            set
            {
                this.planForLandRegisterField = value;
            }
        }

        /// <remarks/>
        public Map PlanForLandRegisterMainPage
        {
            get
            {
                return this.planForLandRegisterMainPageField;
            }
            set
            {
                this.planForLandRegisterMainPageField = value;
            }
        }

        /// <remarks/>
        public extensions extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public enum CantonCode
    {

        /// <remarks/>
        ZH,

        /// <remarks/>
        BE,

        /// <remarks/>
        LU,

        /// <remarks/>
        UR,

        /// <remarks/>
        SZ,

        /// <remarks/>
        OW,

        /// <remarks/>
        NW,

        /// <remarks/>
        GL,

        /// <remarks/>
        ZG,

        /// <remarks/>
        FR,

        /// <remarks/>
        SO,

        /// <remarks/>
        BS,

        /// <remarks/>
        BL,

        /// <remarks/>
        SH,

        /// <remarks/>
        AR,

        /// <remarks/>
        AI,

        /// <remarks/>
        SG,

        /// <remarks/>
        GR,

        /// <remarks/>
        AG,

        /// <remarks/>
        TG,

        /// <remarks/>
        TI,

        /// <remarks/>
        VD,

        /// <remarks/>
        VS,

        /// <remarks/>
        NE,

        /// <remarks/>
        GE,

        /// <remarks/>
        JU,

        /// <remarks/>
        FL,
    }

    public partial class GeneralInformation
    {
        private LocalisedMText[] localisedText;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LocalisedText", IsNullable = false)]
        public LocalisedMText[] LocalisedText
        {
            get
            {
                return this.localisedText;
            }
            set
            {
                this.localisedText = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Glossary
    {

        private LocalisedText[] titleField;

        private LocalisedMText[] contentField;

        private extensions extensionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedMText[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        public extensions extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

}