//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oereb.Service.DataContracts.Model.v20
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("coord", Namespace = "http://www.interlis.ch/geometry/1.0", IsNullable = false)]
    public partial class CoordType : GeometryType
    {

        private double c1Field;

        private double c2Field;

        private double c3Field;

        private bool c3FieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public double c1
        {
            get
            {
                return this.c1Field;
            }
            set
            {
                this.c1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public double c2
        {
            get
            {
                return this.c2Field;
            }
            set
            {
                this.c2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public double c3
        {
            get
            {
                return this.c3Field;
            }
            set
            {
                this.c3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c3Specified
        {
            get
            {
                return this.c3FieldSpecified;
            }
            set
            {
                this.c3FieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SurfaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolylineType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CoordType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("geometry", Namespace = "http://www.interlis.ch/geometry/1.0", IsNullable = false)]
    public abstract partial class GeometryType
    {

        private extensions1 extensionsField;

        private string epsgField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public extensions1 extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string epsg
        {
            get
            {
                return this.epsgField;
            }
            set
            {
                this.epsgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/geometry/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("extensions", Namespace = "http://www.interlis.ch/geometry/1.0", IsNullable = false)]
    public partial class extensions1
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("surface", Namespace = "http://www.interlis.ch/geometry/1.0", IsNullable = false)]
    public partial class SurfaceType : GeometryType
    {

        private BoundaryType[] exteriorField;

        private BoundaryType[] interiorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("exterior", Order = 0)]
        public BoundaryType[] exterior
        {
            get
            {
                return this.exteriorField;
            }
            set
            {
                this.exteriorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("interior", Order = 1)]
        public BoundaryType[] interior
        {
            get
            {
                return this.interiorField;
            }
            set
            {
                this.interiorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class BoundaryType
    {

        private PolylineType polylineField;

        /// <remarks/>
        public PolylineType polyline
        {
            get
            {
                return this.polylineField;
            }
            set
            {
                this.polylineField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("polyline", Namespace = "http://www.interlis.ch/geometry/1.0", IsNullable = false)]
    public partial class PolylineType : GeometryType
    {

        private CoordType coordField;

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CoordType coord
        {
            get
            {
                return this.coordField;
            }
            set
            {
                this.coordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("arc", typeof(ArcSegmentType), Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("coord", typeof(CoordType), Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("customLineSegment", typeof(LineSegmentType), Order = 1)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class ArcSegmentType : LineSegmentType
    {

        private double a1Field;

        private double a2Field;

        private double rField;

        private bool rFieldSpecified;

        /// <remarks/>
        public double a1
        {
            get
            {
                return this.a1Field;
            }
            set
            {
                this.a1Field = value;
            }
        }

        /// <remarks/>
        public double a2
        {
            get
            {
                return this.a2Field;
            }
            set
            {
                this.a2Field = value;
            }
        }

        /// <remarks/>
        public double r
        {
            get
            {
                return this.rField;
            }
            set
            {
                this.rField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rSpecified
        {
            get
            {
                return this.rFieldSpecified;
            }
            set
            {
                this.rFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArcSegmentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StraightSegmentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StartSegmentType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("customLineSegment", Namespace = "http://www.interlis.ch/geometry/1.0", IsNullable = false)]
    public abstract partial class LineSegmentType
    {

        private extensions1 extensionsField;

        private double c1Field;

        private double c2Field;

        private double c3Field;

        private bool c3FieldSpecified;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public extensions1 extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public double c1
        {
            get
            {
                return this.c1Field;
            }
            set
            {
                this.c1Field = value;
            }
        }

        /// <remarks/>
        public double c2
        {
            get
            {
                return this.c2Field;
            }
            set
            {
                this.c2Field = value;
            }
        }

        /// <remarks/>
        public double c3
        {
            get
            {
                return this.c3Field;
            }
            set
            {
                this.c3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c3Specified
        {
            get
            {
                return this.c3FieldSpecified;
            }
            set
            {
                this.c3FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class StraightSegmentType : LineSegmentType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class StartSegmentType : LineSegmentType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("multisurface", Namespace = "http://www.interlis.ch/geometry/1.0", IsNullable = false)]
    public partial class MultiSurfaceType
    {

        private SurfaceType surfaceField;

        /// <remarks/>
        public SurfaceType surface
        {
            get
            {
                return this.surfaceField;
            }
            set
            {
                this.surfaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("multicoord", Namespace = "http://www.interlis.ch/geometry/1.0", IsNullable = false)]
    public partial class MultiCoordType
    {

        private CoordType coordField;

        /// <remarks/>
        public CoordType coord
        {
            get
            {
                return this.coordField;
            }
            set
            {
                this.coordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("multipolyline", Namespace = "http://www.interlis.ch/geometry/1.0", IsNullable = false)]
    public partial class MultiPolylineType
    {

        private PolylineType polylineField;

        /// <remarks/>
        public PolylineType polyline
        {
            get
            {
                return this.polylineField;
            }
            set
            {
                this.polylineField = value;
            }
        }
    }

}